FROM mcr.microsoft.com/dotnet/sdk:5.0

# Copy files to app directory
COPY . /app

# Set working directory
WORKDIR /app/CommandF.Feed.Importer

# Restore NuGet packages
RUN ["dotnet", "restore"]

# Build the app
RUN dotnet build -c Release -o /bin

# Run the app
WORKDIR /bin

# Run the app
ENTRYPOINT ["dotnet", "CommandF.Feed.Importer.dll"]
